version: '3'

services:

  maps:
    container_name: load_maps
    build: 
      context : ./flask_app
      dockerfile : Dockerfile.load
    volumes: 
      - ./flask_app:/app
    command: python get_maps.py
    

  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
    depends_on:
      - maps


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app


  
